### PR TITLE
Update to latest ESLint and nightmare-mode.

### LINKED ISSUE #6: Update ESLint to 2.x
Hi,

currently available version of ESLint is 2.1.0. I think your dependencies should be updated. Also `index.js` should contain rules matching to those available now in the newest version of ESLint. Now, when I'm using `eslint-config-ember` with ESLint 2.1.0 I get that in test output: 
```bash
1:1  - Rule 'no-extra-strict' was removed and replaced by: strict (no-extra-strict)
1:1  - Rule 'no-wrap-func' was removed and replaced by: no-extra-parens (no-wrap-func)
1:1  - Rule 'spaced-line-comment' was removed and replaced by: spaced-comment (spaced-line-comment)
```

I can prepare PR if you want.

Regrads

### PR DESCRIPTION
**Pull request by chriskrycho**
Resolves #6. Note, however, that this does _not_ resolve the estraverse-fb issue that crops up in many tools which _also_ use this because of the babel-eslint dependency. Those tools need to update to `babel-eslint` at 6.0.0-beta.6 or higher.

### CODE REVIEW

**Comment by chriskrycho** [comment]
One other note, @jonathanKingston: this is a small enough repo I'm happy to help maintain it. Probably will be a free-time only project, but even so, I can manage it. :smile:

**Comment by chriskrycho** [comment]
@jonathanKingston, just checking in. I know you're busy with other stuff, but this is a blocker for us and is at the bottom of a dependency chain, so dealing with a fork would mean dealing with at least *three* forks. Again, I'm happy to be a (co-)maintainer so you don't have to maintain stuff you're not using.

**Comment by coladarci** [comment]
:+1: - @chriskrycho thanks for this - we are in a world of pain as well and this would help a lot!

**Comment by jonathanKingston** [comment]
Looks good was merging, was away all week sorry.

**Comment by chriskrycho** [comment]
Ah, was wondering! No worries. 😄 As mentioned, happy to be a co-maintainer and take it off your "must maintain in free time" plate; we're using this and I'm happy to help shepherd it along!

**Comment by jonathanKingston** [comment]
Will consider for the next position certainly, I added Brian for now. Not sure we need loads of maintainers for a small repo. Thanks!

**Comment by chriskrycho** [comment]
No worries; doesn't matter to me as long as we're helping clear your plate a bit!

**Pull request merged**
